spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda:
  bpm:
    generic-properties:
      properties:
        enforceHistoryTimeToLive: false
    admin-user:
      id: demo
      password: demo